name: 'T&L Ministries'
favicon: null
layout_spectrum: 0.2401
typography_spectrum: 0.51404
title: 'T&L Ministries'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4db7ad'
    - '#000000'
    - '#593192'
    - '#cbbedc'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
