name: 'T&L Ministries'
favicon: null
layout_spectrum: 0.4505
typography_spectrum: 0.67493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4db7ad'
    - '#000000'
    - '#593192'
    - '#cbbedc'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
